### ISSUE TITLE
hash and set are implemented but unchecked in readme?

### ISSUE THREAD

**Issue by yangmls** [meitu/titan#6]
the project is awesome, thanks for the great work!

I found the hget/hset/sadd etc are implemented in the command package but still be unchecked in readme, what is the reason?

**Comment by shafreeck** [comment]
The codes about hashes and set do not complete so far, we are coding on hashes now.

**Comment by yangmls** [comment]
do you plan to change the meta structure for hash and/or set? If it will be compatible for future version, we would like to try it in production

**Comment by shafreeck** [comment]
There is a problem with hashes that it causes many conflicts when updating a hash because we should increment its size which is maintained by a single key.

Now we are planning to use multiple meta keys for a hash to reduce the transaction conflicts. Would you like to describe your scenarios to use hashes?
